name: Auto merge dependencies
on:
  pull_request:
    branches:
      - dependabot_develop
    paths:
      - yarn.lock
      - package.json

jobs:
  automerge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
