#
# This workflow runs on push | pull_request events of the develop branch
#
# It will publish storybook to Chromatic.
#

name: 'Chromatic'

on:
  push:
    branches:
      - develop
    paths:
      - yarn.lock
      - stories/**
      - packages/**
      - .storybook/**
  pull_request:
    branches:
      - develop
    paths:
      - yarn.lock
      - stories/**
      - packages/**
      - .storybook/**

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      #
      # Checkout the project
      #
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #
      # Cache files
      #
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            node_modules/
            .eslintcache
            **/.cache
            packages/**/node_modules/
          key: ${{ github.ref }}-styled-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ github.ref }}-styled-

      #
      # Install dependencies
      #
      - name: Build components
        run: yarn install --frozen-lockfile && yarn bootstrap && yarn build

      #
      # Publish storybook on Chromatic and accept changes.
      #
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        if: ${{ github.actor != 'dependabot[bot]' && github.event.pull_request.draft == false }}
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          autoAcceptChanges: github.ref == 'refs/heads/develop'
          exitOnceUploaded: github.ref != 'refs/heads/develop'
